version: "3.9"
services:
  dicom_app:
    build: .
    container_name: dicom_app
    ports:
      - "8017:8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped
